### PR TITLE
Implementation of content_for? method to check if a given content was defined (similar to Rails)

### PR DESCRIPTION
**Pull request by brunograsselli**
Implementation of content_for? method to check if a given content was defined (similar to Rails).
Also, the content_for_test.rb was updated to work with latest Sinatra release (1.1.2, as for now) and use Rack::Test::Methods instead of old Sinatra::Test.

### CODE REVIEW

**Comment by akzhan** [comment]
adopted and merged into sinatra-content-for2.

**Comment by brunograsselli** [comment]
Thanks.

What's the difference between sinatra-content-for and sinatra-content-for2?

**Comment by akzhan** [comment]
It's simply a fork that supports Erubis, Bundler and has altered gem name.

**Comment by foca** [comment]
Um, sorry I just caught up with this. You should both contribute to sinatra-contrib, which includes an updated version of content-for.

**Pull request closed without merging**
